language: cpp
before_script:
- echo "gtest routine"
- sudo apt-get -qq update
- sudo apt-get install -y libgtest-dev valgrind cmake
- sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
- sudo tar xf release-1.7.0.tar.gz
- cd googletest-release-1.7.0
- sudo cmake -DBUILD_SHARED_LIBS=ON .
- sudo make
- sudo cp -a include/gtest /usr/include
- sudo cp -a libgtest_main.so libgtest.so /usr/lib/
- mkdir tmp && cd tmp
- sudo wget https://github.com/google/googlemock/archive/release-1.7.0.tar.gz
- sudo tar xf release-1.7.0.tar.gz
- cd googlemock-release-1.7.0
- sudo cmake -DBUILD_SHARED_LIBS=ON .
- sudo make
- sudo cp -a include/gmock /usr/include
- sudo cp -a libgmock_main.so libgmock.so /usr/lib/
- which valgrind
- cd "${TRAVIS_BUILD_DIR}"
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- exec hellotest
- exec valgrind helloworld_cli
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T 