language: cpp
before_script:
- echo "gtest routine"
- sudo apt-get -qq update
- sudo apt-get install -y libgtest-dev valgrind cmake git
- sudo git clone https://github.com/google/googletest/
- cd googletest
- sudo cmake -DBUILD_SHARED_LIBS=ON .
- sudo make
- sudo cp -a googletest/include/gtest /usr/include
- sudo cp -a googlemock/include/gmock /usr/include
- sudo cp -a lib/libgtest_main.so lib/libgtest.so lib/libgmock_main.so lib/libgmock.so /usr/lib/
- which valgrind
- cd "${TRAVIS_BUILD_DIR}"
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- valgrind --verbose ./helloworld_cli
deploy:
  provider: script
  skip_cleanup: true
  script: curl -T just_for_fun-0.10.$TRAVIS_BUILD_NUMBER-Linux.deb -ule0nx:$BINTRAYKEY "https://api.bintray.com/content/le0nx/test_ci/HW1/$TRAVIS_BUILD_NUMBER/just_for_fun-0.10.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"